module.exports = {
  ENV: process.env.NODE_ENV || 'development',
  PORT: process.env.PORT || 8443,
  HOST: process.env.HOST || '::1',
  cert_path: process.env.cert_path || '../cert/',
  cert: process.env.cert || 'cert.pem',
  key: process.env.key || 'key.pem',
  jwt_secret: process.env.jwt_secret || '',
  jwt_key_path: process.env.jwt_key_path || '../key/',
  jwt_key_prv: process.env.jwt_key_prv || 'jwtRS256.key',
  jwt_key_pub: process.env.jwt_key_pub || 'jwtRS256.pem',
  allowHTTP1: process.env.allowHTTP1 || 'true',
  MONGODB_URI: process.env.MONGODB_URI || 'mongodb://localhost/',
  DB_NAME: process.env.DB_NAME || 'Bleeper',
};
